import json

# here should be the data path generated by printInfo
with open("scripts/defInfos.json", 'r') as fp:
  data = json.load(fp)

def generate_latex_content(json_data):
    definitions = []
    lemmas = []

    for item in json_data:
        name = item["name"]
        module = item["module"]
        is_thm = item["isThm"]
        is_sorry = item["isSorry"]
        docstring = item["docstring"]
        uses = item["uses"]

        lean_ok = "\\leanok" if not is_sorry else ""
        lean_ref = f"\\lean{{{name}}}"
        uses_content = ""
        if uses:
            uses_list = ",\n    ".join([f"{{{u}}}" for u in uses])
            uses_content = f"\\uses{uses_list}"


        content = f"""
        \\begin{{definition}}\\label{{{name}}}
          {lean_ref}
          {lean_ok}
          {uses_content}
          {docstring if docstring else ""}
        \\end{{definition}}""" if not is_thm else f"""
        \\begin{{lemma}}\\label{{{name}}}
          {lean_ref}
          {lean_ok}
          {uses_content}
          {docstring if docstring else ""}
        \\end{{lemma}}"""

        if is_thm:
            lemmas.append(content)
        else:
            definitions.append(content)

    latex_output = f"""
    \\chapter{{Definitions}}
    {'\n'.join(definitions)}

    \\chapter{{Lemmas}}
    {'\n'.join(lemmas)}"""

    return latex_output

latex_content = generate_latex_content(data)

with open("scripts/content.tex", 'w', encoding='utf-8') as f:
  f.write(latex_content)